// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedGreenBlue.Data;

#nullable disable

namespace RedGreenBlue.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RedGreenBlue.Models.Cell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamColor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamColor", "Position")
                        .IsUnique();

                    b.ToTable("Cells");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HexColor = "#CCCCCC",
                            Position = 0,
                            TeamColor = 0
                        },
                        new
                        {
                            Id = 2,
                            HexColor = "#CCCCCC",
                            Position = 1,
                            TeamColor = 0
                        },
                        new
                        {
                            Id = 3,
                            HexColor = "#CCCCCC",
                            Position = 2,
                            TeamColor = 0
                        },
                        new
                        {
                            Id = 4,
                            HexColor = "#CCCCCC",
                            Position = 3,
                            TeamColor = 0
                        },
                        new
                        {
                            Id = 5,
                            HexColor = "#CCCCCC",
                            Position = 4,
                            TeamColor = 0
                        },
                        new
                        {
                            Id = 6,
                            HexColor = "#CCCCCC",
                            Position = 5,
                            TeamColor = 0
                        },
                        new
                        {
                            Id = 7,
                            HexColor = "#CCCCCC",
                            Position = 6,
                            TeamColor = 0
                        },
                        new
                        {
                            Id = 8,
                            HexColor = "#CCCCCC",
                            Position = 7,
                            TeamColor = 0
                        },
                        new
                        {
                            Id = 9,
                            HexColor = "#CCCCCC",
                            Position = 8,
                            TeamColor = 0
                        },
                        new
                        {
                            Id = 10,
                            HexColor = "#CCCCCC",
                            Position = 0,
                            TeamColor = 1
                        },
                        new
                        {
                            Id = 11,
                            HexColor = "#CCCCCC",
                            Position = 1,
                            TeamColor = 1
                        },
                        new
                        {
                            Id = 12,
                            HexColor = "#CCCCCC",
                            Position = 2,
                            TeamColor = 1
                        },
                        new
                        {
                            Id = 13,
                            HexColor = "#CCCCCC",
                            Position = 3,
                            TeamColor = 1
                        },
                        new
                        {
                            Id = 14,
                            HexColor = "#CCCCCC",
                            Position = 4,
                            TeamColor = 1
                        },
                        new
                        {
                            Id = 15,
                            HexColor = "#CCCCCC",
                            Position = 5,
                            TeamColor = 1
                        },
                        new
                        {
                            Id = 16,
                            HexColor = "#CCCCCC",
                            Position = 6,
                            TeamColor = 1
                        },
                        new
                        {
                            Id = 17,
                            HexColor = "#CCCCCC",
                            Position = 7,
                            TeamColor = 1
                        },
                        new
                        {
                            Id = 18,
                            HexColor = "#CCCCCC",
                            Position = 8,
                            TeamColor = 1
                        },
                        new
                        {
                            Id = 19,
                            HexColor = "#CCCCCC",
                            Position = 0,
                            TeamColor = 2
                        },
                        new
                        {
                            Id = 20,
                            HexColor = "#CCCCCC",
                            Position = 1,
                            TeamColor = 2
                        },
                        new
                        {
                            Id = 21,
                            HexColor = "#CCCCCC",
                            Position = 2,
                            TeamColor = 2
                        },
                        new
                        {
                            Id = 22,
                            HexColor = "#CCCCCC",
                            Position = 3,
                            TeamColor = 2
                        },
                        new
                        {
                            Id = 23,
                            HexColor = "#CCCCCC",
                            Position = 4,
                            TeamColor = 2
                        },
                        new
                        {
                            Id = 24,
                            HexColor = "#CCCCCC",
                            Position = 5,
                            TeamColor = 2
                        },
                        new
                        {
                            Id = 25,
                            HexColor = "#CCCCCC",
                            Position = 6,
                            TeamColor = 2
                        },
                        new
                        {
                            Id = 26,
                            HexColor = "#CCCCCC",
                            Position = 7,
                            TeamColor = 2
                        },
                        new
                        {
                            Id = 27,
                            HexColor = "#CCCCCC",
                            Position = 8,
                            TeamColor = 2
                        });
                });

            modelBuilder.Entity("RedGreenBlue.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            Team = 0,
                            Username = "admin",
                            isAdmin = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
